DROOLS-3903 DMN Submarine endpoint codegen (#71)
* DROOLS-3814 DMN Submarine Example on Quarkus

* Allegedly external module problems fixed >0.13.1, upgrade to 0.13.3

* Add byName endpoint

* License header

* Downgrade to Quarkus 0.12.0 to test Jenkins CI pipeline

* Try inherit 0.13.1 from submarine BOM (failed locally on 2019-05-16)

* Revert and downgrade again to Quarkus 0.12 for Jenkins CI

* Try with 0.13.1 and Jenkins CI

* Downgrade to Quarkus 0.12.0 for Jenkins CI

Error on Jenkins CI is:
io.quarkus.bootstrap.BootstrapException: Failed to locate current
project among the loaded local projects

locally building fine.

* Align to -runtimes kie-dmn-rest-utils rename

* Implement review feedback

* renaming submarine in kogito (#1)

* Rework using Application injection

* Working ok with generated endpoint for the model

* cleanups

* version alignment for the native maven profile (locally checked)